### ISSUE TITLE
Is this repo still open to work??

### ISSUE THREAD

**Issue by opticSquid** [Sera-iso/React_Weather_APP#1]
I would like to work on this repo.. Will it be fine for you or is this a completed project ?

**Comment by Sera-iso** [comment]
Hi @soumalyatheking22012001 I am still supposed to iterate on this repo.
What work were you thinking of?

**Comment by opticSquid** [comment]
May be I would like to iterate over the UI a bit

**Comment by Sera-iso** [comment]
Sure! feel free to export the code and use it in your project :)
Happy coding!

**Comment by opticSquid** [comment]
Thank you 😊

**Comment by opticSquid** [comment]
I'm closing the issue
